### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by guga31bb** [guga31bb/nfl_data_pipeline#1]
** Offseason **
- [ ] Maybe older data for nflfastR
- [ ] Maybe re-train EP and WP models
- [x] Fetch plays ahead of time for box score site (store some pre-generated tables, allow the possibility for scraping unfetched games, fetch current week games periodically)
- [x] Maybe add win prob to PAT
- [x] Check WP model and one hot encoding

** Done **
- [x] Try re-training WP model
- [x] Get schedule weeks for box score site
- [x] Automate box score updating
- [x] QBs YAC EPA over expected
- [x] Function to get current week
